// ✅ Define Shipping & Checkout Form Data
export interface CheckoutFormData {
    name: string;
    address: string;
    city: string;
    zip: string;
    country: string;
    pointsUsed: number; // ✅ New field for points redemption
    points: number; // ✅ New field for user points
    cartItems: { id: string; title: string; price: number; quantity: number; image: string }[]; // ✅ Correct type
  
  }

  // ✅ Define Order Data Structure
  export interface OrderData {
    orderId?: string; // ✅ Make orderId optional since it's generated by the backend
    userId: string;
    email: string;
    items: CartItem[];
    totalAmount: number;
    status: string;
    trackingCode: string;
    estimatedDelivery?: string; // ✅ Make estimatedDelivery optional
    pointsUsed: number; // ✅ Track points used
    shippingInfo: {
      pointsUsed: number; // ✅ Track points used
      name: string;
      address: string;
      city: string;
      zip: string;
      country: string;
    };
  }

  export interface CartItem {
    id: string;
    title: string; // ✅ Change from "name" to "title"
    price: number;
    quantity: number;
    image: string;
  }